### ISSUE TITLE
/rest/starbucks/pom.xml:Line 87

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-data-examples#117]
/rest/starbucks/pom.xml
Line 87
```xml
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <mainClass>example.stores.StoreApp</mainClass>
    </configuration>
```
But it seems there's no class example.stores.StoreApp, do you means example.springdata.rest.stores.StoreApp

**Comment by olivergierke** [comment]
That's fixed. I removed the declaration entirely as it's obsolete anyway.
