### ISSUE TITLE
How does QUser get created?

### ISSUE THREAD

**Issue by zachariahyoung** [spring-projects/spring-data-examples#133]
I'm having issues with building a sample application of my own.  I can't seem to figure out how the QUser concept is being created.

I'm trying to create a sample using JPA.

**Comment by olivergierke** [comment]
The Querydsl metamodel classes are generated using the APT Maven plugin. You can see a sample configuration [here](https://github.com/spring-projects/spring-data-examples/blob/master/jpa/showcase/pom.xml#L91)

**Comment by zachariahyoung** [comment]
That did the trick.  Thanks

**Comment by olivergierke** [comment]
:+1:
