### ISSUE TITLE
text and geoNear not allowed in same query

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-data-examples#136]
Hey can you guide me how we can use $TextSearch and $geoNear query combine. Please help me I am getting text and geoNear not allowed in same query

**Comment by christophstrobl** [comment]
@JavaHelper please have a look at the [MongoDB Limits](http://docs.mongodb.org/manual/reference/limits/#Queries-cannot-use-both-text-and-Geospatial-Indexes) which do not allow to combine text and geo queries. 

> You cannot combine the $text query, which requires a special text index, with a query operator that requires a different type of special index. For example you cannot combine $text query with the $near operator.

**Comment by JavaHelper** [comment]
Chris - Thank you for Info, but I can't change design, I strictly need to use TextCriteria with $PositionNear and Pageable. Is there any workaround ?

Please guide me as its real problem forme.

```db.user.find({ "position" : { "$nearSphere" : { $java : 
Point [x=73.3123, y=30.520430] },
"$maxDistance" : 0.005432 } }) ```

**Comment by christophstrobl** [comment]
Combining 2 special index structures is not possible using MongoDB. This means that a text index cannot be used together with eg. a geospatial index. 
["$near"](https://docs.mongodb.org/manual/reference/operator/query/near/) requires to operate on a 2d or 2dsphere index and therefore cannot be combined with text search.

However it is possible to use [$geoWithin]() which does not require a geospatial index. Use a `Polygon` or `Circle` for that to construct queries like

	
```javascript
db.text_and_geo.find({
 	 "loc": { "$geoWithin" : { "$geometry": { "type" : "Polygon" , "coordinates": [ [ [ 0, 0 ], [ 3, 6 ], [ 6, 1 ], [ 0, 0 ] ] ] }}},
 	 "$text" : { "$search" : "data"}
})

db.text_and_geo.find({
 	 "loc": { "$geoWithin": { "$center": [ [1, 1], 10 ] } } ,
 	 "$text" : { "$search" : "data"}
})
```

Pretty much the same can be done using `MongoTemplate`

```java
Query queryWithPolygon = TextQuery.queryText(TextCriteria.forDefaultLanguage()
  .matching("spring"))
  .addCriteria(
	where("loc")
	  .within(new GeoJsonPolygon(new Point(0, 0), new Point(3, 6), new Point(6, 1), new Point(0, 0)));
List<TextAndGeo> result = template.find(queryWithPolygon, TextAndGeo.class);

Query queryWithCircle = TextQuery.queryText(TextCriteria.forDefaultLanguage()
  .matching("spring"))
  .addCriteria(
	where("loc")
	  .within(new Circle(new Point(0, 0), 10));
List<TextAndGeo> result = template.find(queryWithCircle, TextAndGeo.class);

```

In case of `Repository` simply use the `Within` keyword for your derived query `Page<TextAndGeo> findByLocWithin(Circle c, TextCriteria tc, Pageable p)`.

**Comment by JavaHelper** [comment]
Thanks for such a great answer. However I see Pageable not working properly for Next and Prev link. for various Pagination sequences. So research on that I found http://stackoverflow.com/questions/24004015/spring-data-mongodb-nearsphere-not-working-with-query-withpageable,  

Could you please guide how we can tackle with these conditions ?
