### ISSUE TITLE
JPA multilevel cascade，how to only query first level filed for restcontroller

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-data-examples#152]
```java
User{
  @OneToMany
   List<Role> roles;
}

Role{
  @OneToMany
  Lisy<Permission> permissions;
}

```

if query user,how can only get roles not load permissions,because jackson convert to json lazy load it

**Comment by olivergierke** [comment]
Please stop opening generic question tickets that are unrelated to any examples in this repository. I haven't had to do this before but I fear we have to ban you from the project otherwise :(.

As indicated in [other](#148) [tickets](#145), please use StackOverflow for generic questions.
