### ISSUE TITLE
No QAccount class in the showcase example

### ISSUE THREAD

**Issue by crossz** [spring-projects/spring-data-examples#156]
`import example.springdata.jpa.showcase.core.QAccount`

This target java class could not be found.

**Comment by olivergierke** [comment]
The class is generated by a [build plugin](https://github.com/spring-projects/spring-data-examples/blob/master/jpa/showcase/pom.xml#L93) either during build or via the Maven integration in your IDE.

**Comment by crossz** [comment]
got it. thanks. when I started VPN, it works fine.....
