### ISSUE TITLE
http://stackoverflow.com/questions/36163606/text-search-not-working-with-spring-boot-mongodb

### ISSUE THREAD

**Issue by JavaNeed** [spring-projects/spring-data-examples#169]
Could you please guide on this issue: http://stackoverflow.com/questions/36163606/text-search-not-working-with-spring-boot-mongodb?

**Comment by mp911de** [comment]
Seriously, please stop opening tickets to make someone reply on StackOverflow. We'll respond when we get to. Generally speaking: the place to ask general questions, is StackOverflow, not the issue tracker.
