### ISSUE TITLE
How can custom `IgnoreNull` like `IgnoreCase` ?

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-data-examples#170]
if deletedAt is null, like use `findById`,remove `deletedAt` from condition，`IgnoreNull`,`AllIgonreNull`
```java
public interface AreaRepository extends CommonJpaRepository<AreaEntity, Integer> {
    AreaEntity findByIdAndDeletedAtIgnoreNull(Integer id,Date deletedAt);

    AreaEntity findByIdAndNameAllIgnoreNull(Integer id,String name);
 }
```

**Comment by mp911de** [comment]
This is not a general discussion forum. Please use StackOverflow for general questions.

**Comment by Dreampie** [comment]
http://stackoverflow.com/questions/36169988/how-can-ignore-null-value-in-spring-data , nobody help

**Comment by mp911de** [comment]
The StackOverflow question is now 3hrs old, seriously, hardly one had even a chance to notice it. If you need support with guaranteed response time, our paid support might be an option for you: http://pivotal.io/labs
