### ISSUE TITLE
examples pom parent incorrect?

### ISSUE THREAD

**Issue by end-user** [spring-projects/spring-data-examples#176]
It looks to me like the web/example project is pointing at the wrong parent.

	<artifactId>spring-data-web-example</artifactId>

	<parent>
		<groupId>org.springframework.data.examples</groupId>
		<artifactId>spring-data-web-examples</artifactId>
		<version>1.0.0.BUILD-SNAPSHOT</version>
	</parent>

Shouldn't it be `spring-data-examples`?

**Comment by mp911de** [comment]
web/example/pom.xml points to its parent project https://github.com/spring-projects/spring-data-examples/tree/master/web. The same pattern is used in the other example modules as well.

**Comment by end-user** [comment]
Oh, I see.  Sorry my mistake.
