### ISSUE TITLE
the cassandra example has compilation error

### ISSUE THREAD

**Issue by missedone** [spring-projects/spring-data-examples#178]
checked out the master branch of cassandra example.
there're several compile failure, for example: https://github.com/spring-projects/spring-data-examples/blob/master/cassandra/example/src/main/java/example/springdata/cassandra/User.java#L43 no `setId` method at all.

so looks like this is just half-way example, or forgot to commit something?
thanks

**Comment by mp911de** [comment]
Hi @missedone,

our examples use [Project Lombok](https://projectlombok.org/) to get rid of boilerplate code. That's the reason you don't see any getters/setters. Your IDE will need a Plugin for either [IntelliJ](https://plugins.jetbrains.com/plugin/6317) or [Eclipse](https://projectlombok.org/download.html) while Maven works out of the box.

**Comment by missedone** [comment]
thanks, good to know
