### ISSUE TITLE
Development environment setup instruction

### ISSUE THREAD

**Issue by hongyan99** [spring-projects/spring-data-examples#187]
May be I'm a bit out-dated on spring data. Today I am trying to experiment with spring-data-mongo. Checked out the sample code in this git project, and was able to do "mvn clean install", so far so good. But then, when I import the maven projects into the latest Eclipse STS, I got a whole bunch of errors pointing to "The blank final field <field name> may not have been initialized". I know what this error means but apparently I am a little outdated with my knowledge in development of spring data application in Eclipse. Googled for over an hour trying to find a solution but no luck so far. Is there an eclipse plugin I'm missing for Eclipse to ignore these blank final fields but still able to compile and run the tests? I was expecting to find some info per how to setup develop environment on working with these sample code in an Eclipse, but the wiki is empty. Would it not make sense to add a page on that in the wiki to help? Thanks.

**Comment by mp911de** [comment]
Hi @hongyan99 
our examples use [Project Lombok](https://projectlombok.org/) to get rid of boilerplate code such as constructors, getter/setter and some more. You will need to install the Eclipse plugin (see [here](https://projectlombok.org/download.html)), so Eclipse can handle also Lombok annotations and does not longer complain about missing code.

**Comment by hongyan99** [comment]
I thought it's got to be something like that :+1: 

Thanks.
