### ISSUE TITLE
Add customer behaviour to all spring data Jpa repositories in CDI context

### ISSUE THREAD

**Issue by ffazil** [spring-projects/spring-data-examples#198]
Am successfully injecting jpa repositories using CDI. I wanted to add custom behaviour(soft deletes) to all repositories. When using spring I can enable customer behaviour by specifying the repository base class

    @EnableJpaRepositories(repositoryBaseClass = StagedRepositoryImpl.class)
How do I specify the same in CDI? Thanks in advance.

**Comment by mp911de** [comment]
This is not a general discussion forum. Please use StackOverflow for general questions.
