### ISSUE TITLE
Spring-data-mongodb+Querydsl:How can build query from mongoTemplate?

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-data-examples#213]
I need excute something before repository query db, but I can't build a query like current repository

http://stackoverflow.com/questions/39928683/spring-data-mongodbquerydslhow-can-build-query-from-mongotemplate

**Comment by mp911de** [comment]
This is not a general discussion forum. Please use StackOverflow for general questions.

**Comment by Dreampie** [comment]
I ask you in gitter，please help
