### ISSUE TITLE
olivergierke ,how to solve this problem 

### ISSUE THREAD

**Issue by 625096233** [spring-projects/spring-data-examples#219]
User.java

@Entity
@Inheritance(strategy=InheritanceType.JOINED)
@DiscriminatorColumn(name = "user_type")
@Table(name = "users")
public class User {.........}

Person.java
@Entity
public class Person extends User {......}

Company.java
@Entity
public class Company extends User {.............}

UserRepository.java
@Transactional
public interface UserRepository extends UserBaseRepository<User> { 
	
	//@Query(value="select u from User u where u.email=?1")
	@Query(value="select u.id,u.email from User u where u.email=?1")
	User getUser(String email);
	
	@Query("select u from User u where u.email=?1")
	User getUser2(String email);
	
	@Query(value="select * from Users where email=:email",nativeQuery=true)
	User getUser3(String email);
	
}

there is a exception blew
Hibernate: select user0_.id as col_0_0_, user0_.email as col_1_0_ from users user0_ where user0_.email=?
org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.Object[] to type netgloo.models.User for value '{1, 635@qq.com}'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.Long to type netgloo.models.User

**Comment by christophstrobl** [comment]
Closing this one. In case of problems and/or questions please use [Stackoverflow](http://stackoverflow.com/tags/spring-data-jpa) or the [issue tracker](https://jira.spring.io/browse/DATAJPA). Thank you.
