### ISSUE TITLE
how to only select the super entity not join the child 

### ISSUE THREAD

**Issue by 625096233** [spring-projects/spring-data-examples#221]
special thanks 
  can you give some suggest about the issues https://github.com/netgloo/spring-boot-samples/issues/4
 how to only select the super entity not join the child

**Comment by 625096233** [comment]
this init project is in https://github.com/monkeylittle/spring-jpa-inheritance
this only diff is i change the user.java (@Inheritance(strategy=InheritanceType.JOINED)) ,because sometime we need only to get the super entity info ,sometime we need the full info

**Comment by 625096233** [comment]
i think there should expose a inteface for user to mapper the resultset t entity,or we can intercept after query finished,but in jpa there only intercept the insert,update ,delete,

**Comment by mp911de** [comment]
Closing this one. In case of problems and/or questions please use [Stackoverflow](http://stackoverflow.com/tags/spring-data-jpa) or the [issue tracker](https://jira.spring.io/browse/DATAJPA). Please refrain from creating such tickets in this Githup repository.
