### ISSUE TITLE
Any example for two cassandra configurations?

### ISSUE THREAD

**Issue by mudpedal** [spring-projects/spring-data-examples#222]
Hello, I am trying to have my spring application connect to two separate sets of cassandra cluster endpoints, with their own tables, keyspaces etc. Is there any good example for this?

I already tried doing it by creating beans with multiple names, have separate properties and configuration classes, in the end there was always an error. Is it even possible?

Thank you and best regards,
Andrei Grigoriu

**Comment by mp911de** [comment]
It's possible by providing all configuration bits regarding `Cluster`, `Session` and `CassandraTemplate` by your own configuration but that kind of set up does not work out of the box.
