### ISSUE TITLE
XML Configuration

### ISSUE THREAD

**Issue by minimok** [spring-projects/spring-data-examples#227]
Would it be too much trouble to leave just one example as an xml-configuration-based? Surely github's  diskspace is not *that* scarce!! :-) 
For people trying to get familiar with which 'components' a spring data project has and how they fit together...xml is vastly superior (the architecture of the app is all in one file) to annotations. Once we get the basics down, naturally annotations are fine...thx.

**Comment by olivergierke** [comment]
I don't think this is going to happen. The examples are supposed to show the state of the art usage of Spring Data, especially in a Spring Boot context where XML configuration plays hardly any role at all.
