### ISSUE TITLE
example.springdata.cassandra.people.ApplicationConfiguration should be "public"

### ISSUE THREAD

**Issue by YannCebron** [spring-projects/spring-data-examples#246]

**Comment by mp911de** [comment]
Is this one still valid?

**Comment by YannCebron** [comment]
AFAIU yes

**Comment by mp911de** [comment]
Care to elaborate why config classes should be public? There's no such requirement in Spring Framework/Spring Boot.

**Comment by YannCebron** [comment]
OK it seems our requirement in IntelliJ IDEA is wrong then here. Please close.

**Comment by mp911de** [comment]
Closing this one, thanks a lot for your feedback.
