### ISSUE TITLE
 when using  redisTemplate.opsForHash() .get()  sometimes can get its value but sometimes can not

### ISSUE THREAD

**Issue by F191919** [spring-projects/spring-data-examples#259]
The following is my project's screenshot 

![f snu4f4zrzyw211 j_0cg](https://cloud.githubusercontent.com/assets/11403274/22852954/0627bda4-f083-11e6-97f0-4649b3324a7b.png)

 
![1486802908 1](https://cloud.githubusercontent.com/assets/11403274/22852961/26ce347a-f083-11e6-8d35-f9b508f53627.jpg)
![1486802989 1](https://cloud.githubusercontent.com/assets/11403274/22852963/29e0ba8e-f083-11e6-814c-1ede5aca2b83.jpg)
![1486802950 1](https://cloud.githubusercontent.com/assets/11403274/22852964/2bd3e8ca-f083-11e6-9132-097d2eb0c7d5.jpg)
 can  you help me ?  thanks

**Comment by mp911de** [comment]
This issue tracker is for bugs or improvement of the examples. If you consider this a bug in Spring Data Redis use its issue tracker https://jira.spring.io/projects/DATAREDIS

If this is just a question about how to use it, ask a question on Stackoverflow https://stackoverflow.com/questions/tagged/spring-data-redis.
