### ISSUE TITLE
Streaming with querydsl

### ISSUE THREAD

**Issue by Ramblurr** [spring-projects/spring-data-examples#260]
This repo includes an example for streaming results:

```java
    @Query("select c from Company c")
    Stream<Company> streamAll();
```

However it would be nice to have an example on how to accomplish the same, but with a QueryDSL Predicate:

```java
    @Query("select c from Company c ..... ?????")
    Stream<Company> streamAll(Predicate predicate);
```

**Comment by petermykytyn** [comment]
i ran into the same issue and i think its not possible with querydsl api
https://jira.spring.io/browse/DATACMNS-704
you have to create your own method that converts iterable to stream if you insist on using stream

**Comment by schauder** [comment]
That is correct, we currently don't have `Stream` support for Querydsl.
