### ISSUE TITLE
Configs with @SpringBootApplication should be public

### ISSUE THREAD

**Issue by YannCebron** [spring-projects/spring-data-examples#261]
At least IntelliJ IDEA does not scan non-public classes for SB applications, which results in all sorts of setup problems in all affected modules.

**Comment by olivergierke** [comment]
So, why does it do that? It's best practice to keep classes in the least public scope they can actually work in, to avoid them being referenced from places they're not even intended to be known.

**Comment by michael-simons** [comment]
So that is way I didn't manage to get SB support in IntelliJ working as good as everybody says it is. Good to know. I second @olivergierke comment, though.

**Comment by YannCebron** [comment]
It seems we mixed up "is runnable Spring application" vs "is annotated with SpringBootApplication" concept in one place. This issue is obsolete then, sorry.
