### ISSUE TITLE
Support for Oracle Stored Procedure - VARRAY types

### ISSUE THREAD

**Issue by ZeroGraviti** [spring-projects/spring-data-examples#267]
I am connecting to an oracle stored procedure which has just one `out` parameter; this is an oracle varray and contains varchars
I am stuck with my `@NamedStoredProcedureQuery` -> `@StoredProcedureParameter(mode = ParameterMode.OUT, name = "MYARRAY", type = ??.class)`
I am not able to set the correct "type" and I have marked as 

> ??.class

I keep getting this exception -> `org.springframework.dao.InvalidDataAccessApiUsageException: Type cannot be null; nested exception is java.lang.IllegalArgumentException: Type cannot be null`
Can someone please help me resolve this ? I made changes to the jpa21 examples which are required for my use case.

**Comment by olivergierke** [comment]
This is the tracker for the examples. For all problems with the individual modules themselves, please raise an issue in in this case [the tracker for Spring Data JPA](https://jira.spring.io/browse/DATAJPA).

**Comment by ZeroGraviti** [comment]
It was roughly based on the jpa21 example. Some pointers/hints would help.

**Comment by olivergierke** [comment]
As it's not a problem with the example per se, this is not the right location. Also, this is an issue tracker, not a general support forum. For general questions, please refer to the [Gitter channel](https://gitter.im/spring-projects/spring-data).

**Comment by ZeroGraviti** [comment]
If it is not too much trouble can you let me know if oracle stored procedures returning VARRAY are supported or planned to be supported ?

**Comment by olivergierke** [comment]
We don't have any database specific stored procedures support but just generally ease the way you'd otherwise interact with stored procedures through JPA.
