### ISSUE TITLE
String Data Neo4j (SDN) example test not storing properties

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-data-examples#268]
The example is not storing properties in the database.  It appears that the tests are passing because the object is being retrieved from Session not from the database.  If I am correct, the example is broken.

`2017-03-21 14:39:51.203  INFO 50155 --- [           main] o.n.o.d.e.request.EmbeddedRequest        : Request: UNWIND {rows} as row CREATE (n:`Actor`) SET n=row.props RETURN row.nodeRef as ref, ID(n) as id, row.type as type with params {rows=[{nodeRef=-827836030, type=node, props={}}]}`

**Comment by ahornbeck** [comment]
Found the issue... properties cannot be `final`.

http://docs.spring.io/spring-data/data-neo4j/docs/4.2.1.RELEASE/reference/html/#reference:annotating-entities:property

**Comment by mp911de** [comment]
This one is outdated, hence closing it.
