### ISSUE TITLE
Is EntityManager thread-safe in the sample of multiple data source?

### ISSUE THREAD

**Issue by hellocomrade** [spring-projects/spring-data-examples#269]
@olivergierke 

https://github.com/spring-projects/spring-data-examples/blob/master/jpa/multiple-datasources/src/test/java/example/springdata/jpa/multipleds/customer/CustomerRepositoryTests.java

I guess the answer is yes, but I'd like to get confirmation from you since you also specifically mentioned here: https://github.com/spring-projects/spring-data-examples/blob/master/jpa/multiple-datasources/src/test/java/example/springdata/jpa/multipleds/customer/CustomerRepositoryTests.java

that such a EntityManager is not safe in web env.

One possibility is that the EntityManager in CustomerRepositoryTests.java is somehow enhanced through proxy, just like @PersistenceContext, which is ThreadLocal and doesn't need to be closed after each call. However, I have trouble to confirm this in any documentation.

Could you please shed some light on this and give me the peace of mind to mimic your sample in my application?

**Comment by schauder** [comment]
The EntityManager itself is not thread safe. But there is one Entity Manager per thread, so it is never accessed from multiple threads. Hence the complete setup is thread safe.

**Comment by hellocomrade** [comment]
@schauder 

Thank you for the explanation! I read the section of Bean Scopes and still felt vague that applying @Qualifier with an entityManagerFactory name on an EntityManager will actually  "scoped-proxy" it to request scope plus auto-close feature... :)
