### ISSUE TITLE
MessageListenerContainer not listening after crashing master redis instance in redis sentinel in docker env.

### ISSUE THREAD

**Issue by chuchiliusandc** [spring-projects/spring-data-examples#283]
Hi All,

I have a question.
I have redis sentinel setup in the docker env. (without docker, things work fine)
I am using the Jedis and redis sentinel support from spring.
RedisMessageListenerContainer is supposed to take care the subscriber part.
However, after shutting down the redis master node, I am able to output the new ip and port from connection factory ... (i.e., the ip and port is referring to the new master).

But ... very often ... All the subscribers become not listening anymore.
Does anyone encounter this issue in docker ?

Thanks :)

**Comment by christophstrobl** [comment]
Closing this one. @chuchiliusandc please use [Stackoverflow](https://stackoverflow.com/questions/tagged/spring-data-redis) for questions. Thank you!
