### ISSUE TITLE
Projection retuen too many field

### ISSUE THREAD

**Issue by benson0217** [spring-projects/spring-data-examples#292]
Hi,
i got some issues like this,
i have two entities,

`
@Entity
public class Person {

  @Id @GeneratedValue
  private Long id;
  private String firstName, lastName;

  @OneToOne
  private Address address;
}

@Entity
public class Address {

  @Id @GeneratedValue
  private Long id;
  private String street, state, country;
}
`

and my projection like this

`
interface PersonLimited {  

  String getFirstName(); 

  AddressLimited getAddress();
}

interface AddressLimited {  

  String getCountry(); 
}
`

repository like this

`
interface PersonRepository extends CrudRepository<Person, Long> {
  PersonLimited findPersonByFirstNameProjectedForLimitedData(String firstName);
}
`

it returns exactly what expected :

{
    firstName: 'Homer',
    address: {
        country: 'USA'
    }
}

now if I look into the generated SQL, this is what I have:

`
SELECT person0_.firstName      AS col_0_0_, 
       address1_.id            AS id1_13_, 
       address1_.street        AS street2_13_, 
       address1_.state         AS state3_13_, 
       address1_.country       AS country4_13_
FROM   person person0_ 
       LEFT OUTER JOIN address address1_ 
                    ON person0_.addressId = address1_.id 
WHERE  person0_.firstName = ?  
`

The projection for the "Person" entity is selecting only "fistName", which is 100% correct because in the PersonLimited interface I've only defined "getFirstName".

But for the "Address" entity, it selects all the fields, which is wrong because in the AddressLimited interface I've only defined "getCountry", It should only select "country".

The generated query should be something like:

`
SELECT person0_.firstName      AS col_0_0_, 
       address1_.country       AS country4_13_
FROM   person person0_ 
       LEFT OUTER JOIN address address1_ 
                    ON person0_.addressId = address1_.id 
WHERE  person0_.firstName = ?  
`

so the question is, why it is not selecting only the "country" field for the Address "entity"? why it needs to select all the fields? is it a bug in Spring data????

**Comment by olivergierke** [comment]
You're right, we currently not optimizing any further as the advanced optimization you suggest would require much deeper inspection and knowledge about the projection interface and severely complicate the implementation.

Feel free to raise a bug in our [JIRA](https://jira.spring.io/browse/DATACMNS) but at the moment I don't think there'd be high priority on this as it's basically about further optimization. The feature does work and produces correct results.

**Comment by benson0217** [comment]
Hi Oliver, 
    thanks a lot for your answer.
by the way , if i use the method in example like
`
@Query("select new example.springdata.jpa.projections.CustomerDto(c.firstname) from Customer c where c.firstname = ?1")
	Collection<CustomerDto> findDtoWithConstructorExpression(String firstname);
` 

Is it possible to achieve this effect?
