### ISSUE TITLE
 Is there any spring-data-jpa example without any spring-boot config？

### ISSUE THREAD

**Issue by duomu** [spring-projects/spring-data-examples#305]
I can't understand the internal details with spring-boot config，for example，which dependencies a simple spring-data-jpa demo needs import.

I tried to create a spring-data-jpa demo without spring-boot or spring parent projects, however, it threw kinds of errors, I searched much，but no help.

hopes for your reply

**Comment by olivergierke** [comment]
No. The point of this example is to showcase how to use Spring Data modules, their APIs and programming concepts, not how to set up dependencies etc. In general you should be fine just depending on the store module you'd like to use and it should pull in all *required* dependencies. For more advanced configurations, looking at what `mvn dependency:tree` lists for the projects here can help finding the libraries you need to import.

If you run into issues with that, posting questions on [StackOverflow](https://stackoverflow.com/) is usually a good way to find advice.
