### ISSUE TITLE
Spring Data JDBC - Demonstrate custom mapping of Maps / Lists

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-examples#316]
How can a mapping to an intermediate table get accomplished?

**Comment by jo2** [comment]
I don't know if this is stil up to date but what exactly do you mean with an intermediate table? a table which is used for heredity? A more comprehensive descrition would be helpful

**Comment by schauder** [comment]
Sorry, this is completely outdated.

Should have closed it a long time ago.
