### ISSUE TITLE
e.s.e.repositories.Address is annotated with @Data and @EqualsAndHashCode

### ISSUE THREAD

**Issue by tanShiLin19981129** [spring-projects/spring-data-examples#318]
some anotation can miss in `package example.springdata.redis.repositories;`  named `Adress`,when i see the `@EqualsAndHashCode` anotation in it's Class ,i'm amazing,i was never use it when i used lombo annotaion to tag the entity/domain/pojo/vo/etc...,so i have a look the source of '@Data',i'm found that some infomation is 
/**
 * Generates getters for all fields, a useful toString method, and hashCode and equals implementations that check
 * all non-transient fields. Will also generate setters for all non-final fields, as well as a constructor.
 * <p>
 * Equivalent to {@code @Getter @Setter @RequiredArgsConstructor @ToString @EqualsAndHashCode}.
 * <p>
 * Complete documentation is found at <a href="https://projectlombok.org/features/Data">the project lombok features page for &#64;Data</a>.
 * 
 * @see Getter
 * @see Setter
 * @see RequiredArgsConstructor
 * @see ToString
 * @see EqualsAndHashCode
 * @see lombok.Value
 */
so that the @EqualsAndHashCode is not necessary to use it in `Address` Class head.

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Indeed, types annotated with `@Data` do not require `@EqualsAndHashCode` unless they want to specify any further attributes in `@EqualsAndHashCode(…)`. It makes sense to `@EqualsAndHashCode` from `Address`.

**Comment by mp911de** [comment]
That's fixed now.
