### ISSUE TITLE
@GeoPointField can't convert camel-case to underscores

### ISSUE THREAD

**Issue by Gegoiuty** [spring-projects/spring-data-examples#320]
This is the GeoPoint field:
![2](https://user-images.githubusercontent.com/5738688/32906586-49a9f552-cb38-11e7-82c1-ea50fd86c301.png)

Add this in model:
```
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
```

And this is the mappings:
![1](https://user-images.githubusercontent.com/5738688/32906777-f3902ca8-cb38-11e7-860c-a595782f071f.png)

Obviously, PropertyNamingStrategy.SnakeCaseStrategy works for @Field, but not work for @GeoPointField.

How can I solve this problem?

**Comment by olivergierke** [comment]
Would you mind raising a bug in the [Spring Data MongoDB issue tracker](https://jira.spring.io/browse/DATAMONGO)?
