### ISSUE TITLE
Spring Data JPA - Demonstrate usage of JPA 2.1 @SqlResultSetMapping

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-data-examples#330]

**Comment by schauder** [comment]
Hi @thomasdarimont, not sure if I'm missing something, but from a Spring Data perspective this is a pure named query, right?

**Comment by thomasdarimont** [comment]
Hi Jens, 

I'm not sure what you mean - this example shows how to use a JPA named native query 
with a custom result set mapping that works well with value objects.
Yes the Spring Data Repository maps the named query to the query method. 
It just shows demonstrates that everything works together.

**Comment by olivergierke** [comment]
I've augmented and merged #331 and also ported it back to 1.x.
