### ISSUE TITLE
Describe default media type for PATCH

### ISSUE THREAD

**Issue by binkley** [spring-projects/spring-data-examples#338]
(If this is the wrong repo to file this issue, please note this and I will correct.)

_Spring Data REST - Reference Documentation_ is outstanding documentation.  However, it does not list the default media type for PATCH.  It does list the supported media types (https://docs.spring.io/spring-data/rest/docs/current/reference/html/#_patch), nor does it list how to configure this (if that is possible).

It would be helpful to add explicit language such as "PATCH does not have a default media type", etc.

**Comment by olivergierke** [comment]
Please raise this issue in [Spring Data RESTs tracker](https://jira.spring.io/browse/DATAREST).
