### ISSUE TITLE
Spring data -jpa is not catching the Store proc raise error messages

### ISSUE THREAD

**Issue by mas222r** [spring-projects/spring-data-examples#356]
I have created simple store proc which is giving result using select statement (which has json_query) and throwing some error message  if some conditions are not met.

sample code in java is  

StoredProcedureQuery query = entityManager.createNamedStoredProcedureQuery("store_proc_name");
query.setParameter("id",23);
query.getResultList();

the above code is not catching SQL raised error message .

Could anybody help me how to catch the sql raised error message ..

**Comment by schauder** [comment]
This issue tracker is for bugs or improvement of the examples. If you consider this a bug in spring data JPA use its issue tracker https://jira.spring.io/projects/DATAJPA 

If this is just a question about how to use it, ask a question on Stackoverflow https://stackoverflow.com/questions/tagged/spring-data-jpa

**Comment by helderhernandez** [comment]
If you want to capture in a try-catch (in java) the errors issued by throw (in sql server) you should consider the following:

- Correctly issue the error in the stored procedure
- Use the **@Query annotation with the nativeQuery option** in java (⚠️ if instead of @Query you use @Procedure **you will not be able to capture the throw**)

I share an example that I developed recently:

### SQL Server - Store procedure
_Note: I perform the update before validations, because I want to generate a table lock (business requirement)_
```sql
CREATE PROCEDURE [dbo].[USP_DT_ModificarResolucion]
	@DocumentoTributario NVARCHAR(25),
	@Resolucion NVARCHAR(25),
	@CantidadTiraje INT
AS BEGIN

	-- bloque try
	BEGIN TRY
		-- start transaction
		BEGIN TRAN
			-- VARIABLES
			DECLARE @OldResolucion NVARCHAR(25)
			DECLARE @CorrelativosEmitidos INT

			-- ACTUALIZACION (MODIFICACION) EN RESOLUCION
			UPDATE [DocumentoTributarioResolucion]
				SET	
				@OldResolucion = [Resolucion], 
				@CorrelativosEmitidos = CAST([UltimoCorrelativoUtilizado] AS INT), 
				[Resolucion] = @Resolucion,
				[CantidadTiraje] = @CantidadTiraje
			WHERE [DocumentoTributario] = @DocumentoTributario

			-- validations
			IF (@OldResolucion IS NULL OR DATALENGTH(@OldResolucion) = 0)
			BEGIN
				-- jump to cath
				DECLARE @errorMessage1 NVARCHAR(100) = 'Aun no se ha establecido una resolucion para el documento ' + @DocumentoTributario;
				THROW 50001, @errorMessage1, 1
			END
			ELSE IF (@CantidadTiraje < @CorrelativosEmitidos)
			BEGIN
				-- jump to cath
				DECLARE @errorMessage2 NVARCHAR(100) = 'No se puede actualizar la tamaño del tiraje porque el valor es menor al ultimo correlativo emitido';
				THROW 50001, @errorMessage2, 1
			END

		-- commit :D
		COMMIT TRAN
	END TRY

	-- bloque catch	
	BEGIN CATCH		
		-- rollback :(
		IF @@TRANCOUNT > 0 ROLLBACK;
		-- re-throw exception
		THROW;
	END CATCH
END
```

### Spring - Repository
```java
public interface IDTResolucionJpa extends JpaRepository<DTResolucionEntity, String> {	
	@Transactional
	@Query(nativeQuery = true, value = "EXECUTE USP_DT_ModificarResolucion "
			+ "@DocumentoTributario = :DocumentoTributario, "
			+ "@Resolucion = :Resolucion, "
			+ "@CantidadTiraje = :CantidadTiraje")
	void USP_DT_ModificarResolucion(
			@Param("DocumentoTributario") String DocumentoTributario,
			@Param("Resolucion") String Resolucion,
			@Param("CantidadTiraje") int CantidadTiraje);
}
```

In java you can use try-catch to get the throw error (which was issued from the db)
```java
try {
	resolucionJpa.USP_DT_ModificarResolucion(documentoTributario, resolucion, cantidadTiraje);
} catch (Exception exception ) {
	// exception.getCause().getCause() contains throw error description of sql server 🤓 
	System.err.println(exception.getCause().getCause()); 

	// your logic to re-throw error
}
```
