### ISSUE TITLE
Cannot find spring-data-jdbc from repo

### ISSUE THREAD

**Issue by imben1109** [spring-projects/spring-data-examples#372]
I cannot find spring-data-jdbc from https://repo.spring.io/libs-milestone and https://repo.maven.apache.org/maven2/.
Is it depreciated?

**Comment by olivergierke** [comment]
It's [here](https://repo.spring.io/libs-milestone/org/springframework/data/spring-data-jdbc/).

**Comment by imben1109** [comment]
Thanks a lot.

 ```
<dependency>
	<groupId>org.springframework.data</groupId>
     	<artifactId>spring-data-jdbc</artifactId>
     	<version>1.0.0.M3</version>
</dependency>
```
