### ISSUE TITLE
@NamedStoredProcedureQuery with procedurename from env variable 

### ISSUE THREAD

**Issue by JanakiramanChandrasekran** [spring-projects/spring-data-examples#383]
Can i populate the procedure dynamic replaced from property file.. I tried multiple ways but looks like the property is not able to resolve. When i use annotation, is it limited by hard coded values only? can i have some code examples to replace dynamically from config/ property file.

@Entity
@NamedStoredProcedureQuery(
        procedureName = "${sp.name}",
        name = "customsp", parameters = {
        @StoredProcedureParameter(mode = ParameterMode.IN, name = "ID", type = String.class),
        @StoredProcedureParameter(mode = ParameterMode.OUT, name = "ID_OUT", type = String.class)})
public class StoredProcResponse implements Serializable {

**Comment by schauder** [comment]
Sorry, this is the issue tracker for Spring Data Examples. Issues here should be

* Bug reports for the examples
* Feature/Improvement requests for the examples.

Yours is a question about how to use Spring Data. The right place for those is StackOverflow. Actually the answer is already there (it applies to your case as well): https://stackoverflow.com/a/1208477/66686
