### ISSUE TITLE
How to dependency injection in ExtendedJpaRepository

### ISSUE THREAD

**Issue by xiubooo** [spring-projects/spring-data-examples#384]
path:
spring-data-examples/jpa/example/src/main/java/example/springdata/jpa/customall/ExtendedJpaRepository.java

I want dependency injection in ExtendedJpaRepository but @Autowired doesn't work.
I understand this don't work is because ExtendedJpaRepository not created by @Autowired.
how can I dependency injection in ExtendedJpaRepository ?

the code look like this 
```
public class BaseRepositoryImpl<T extends BaseEntity, ID extends Serializable>
        extends SimpleJpaRepository<T, ID> implements BaseRepository<T, ID> {

  @Autowired
  private SnowFlake snowFlake;  // dependency injection is null

  private final EntityManager entityManager;
  private final EntityInformation entityInformation;

  public BaseRepositoryImpl(JpaEntityInformation entityInformation,
                            EntityManager entityManager) {
    super(entityInformation, entityManager);
    this.entityInformation = entityInformation;
    this.entityManager = entityManager;
  }
}

**Comment by schauder** [comment]
Sorry, this is the issue tracker for Spring Data Examples. Issues here should be 
- Bug reports for the examples
- Feature/Improvement requests for the examples.

Yours is a question about how to use Spring Data. The right place for those is StackOverflow.
