### ISSUE TITLE
spring-data-redis 1.7.5.RELEASE JedisMovedDataException

### ISSUE THREAD

**Issue by a123demi** [spring-projects/spring-data-examples#397]
Hi all,

the following exception occurs on individual nodes when using spring-data-redis 1.7.5.RELEASE and redis-clients 2.8.1.

MOVED 8046 101.20.93.23:6381 redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 8046 101.20.93.23:6381 at redis.clients.jedis.Protocol.processError(Protocol.java:109) at redis.clients.jedis.Protocol.process(Protocol.java:151) at redis.clients.jedis.Protocol.read(Protocol.java:205) at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297) at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233) at redis.clients.jedis.BinaryJedis.hkeys(BinaryJedis.java:912) at redis.clients.jedis.Jedis.hkeys$accessor$227sP7Mw(Jedis.java) at redis.clients.jedis.Jedis$auxiliary$aDtjRhJJ.call(Unknown Source)  at redis.clients.jedis.Jedis.hkeys(Jedis.java) at redis.clients.jedis.BinaryJedisCluster$38.execute(BinaryJedisCluster.java:446) at redis.clients.jedis.BinaryJedisCluster$38.execute(BinaryJedisCluster.java:443) at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:119) at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131) at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:59) at redis.clients.jedis.BinaryJedisCluster.hkeys(BinaryJedisCluster.java:448) at org.springframework.data.redis.connection.jedis.JedisClusterConnection.hKeys(JedisClusterConnection.java:2356) at org.springframework.data.redis.core.DefaultHashOperations$5.doInRedis(DefaultHashOperations.java:101) at org.springframework.data.redis.core.DefaultHashOperations$5.doInRedis(DefaultHashOperations.java:98) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:204) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:166) at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:88) at org.springframework.data.redis.core.DefaultHashOperations.keys(DefaultHashOperations.java:98) at org.springframework.data.redis.core.DefaultBoundHashOperations.keys(DefaultBoundHashOperations.java:78) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at <generated>)  com.alibaba.dubbo.common.bytecode.Wrapper6.invokeMethod(Wrapper6.java) at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:70) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:113) at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84) at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170) at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) exName: redis.clients.jedis.exceptions.JedisMovedDataException”

spring-redis config is as follows：
`
<bean id="resourcePropertySource" class="org.springframework.core.env.MapPropertySource">
    <constructor-arg name="name" value="redis.config" />
    <constructor-arg name="source">
        <map>
            <entry key="spring.redis.cluster.nodes" value="${redis.cluster.nodes}"/>
            <entry key="spring.redis.cluster.max-redirects" value="${redis.max.redirection}"/>
        </map>
    </constructor-arg>
</bean>
<bean id="redisClusterConfiguration"
      class="org.springframework.data.redis.connection.RedisClusterConfiguration">
    <constructor-arg ref="resourcePropertySource" />
</bean>

<bean id="jedisPoolConfig" class="redis.clients.jedis.JedisPoolConfig">
    <property name="maxTotal" value="${redis.pool.maxTotal:1000}" />
    <property name="maxIdle" value="${redis.pool.maxIdle:100}" />
    <property name="maxWaitMillis" value="${redis.pool.maxWaitMillis:100}" />
    <property name="testOnBorrow" value="${redis.pool.testOnBorrow:false}" />
</bean>
<bean id="jedisConnFactory"
      class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory">
    <constructor-arg ref="redisClusterConfiguration" />
    <constructor-arg ref="jedisPoolConfig" />
    <property name="timeout" value="${redis.pool.timeout:10000}"/>
</bean>

<bean id="defaultSerializer"
      class="org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer" />
<bean id="redisTemplate" class="org.springframework.data.redis.core.RedisTemplate">
    <property name="connectionFactory" ref="jedisConnFactory" />
    <property name="defaultSerializer" ref="defaultSerializer" />
</bean>
`

Thanks.

**Comment by christophstrobl** [comment]
Please use the [bug tracker](https://jira.spring.io/projects/DATAREDIS/) to report issues with one of the projects. Thanks!
