### ISSUE TITLE
Split Spring Data JDBC example into mutable and imutable.

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-examples#398]
We should have separate examples in order to make it easier to compare the approaches.

**Comment by mp911de** [comment]
I'm not quite sure how much we want to mix domain model approaches with our API usage samples. These are orthogonal. While we have some areas we show both approaches (e.g. https://github.com/spring-projects/spring-data-examples/tree/6430790e63df6b7a5f3415fd152e58a6c083a2f7/jdbc/immutables), it doesn't make much sense to host an educational resource for domain model guidance here. There seem to be better places, so I suggest closing this ticket.
