### ISSUE TITLE
Spring Boot Data JPA - @ManyToOne Join with UUID id

### ISSUE THREAD

**Issue by met68** [spring-projects/spring-data-examples#402]
Is [this](https://stackoverflow.com/questions/51990811/spring-boot-data-jpa-manytoone-join-with-uuid-id) a bug or am I just missing something obvious?

Any help would be much appreciated.

**Comment by schauder** [comment]
If it is a bug, it certainly isn't a bug of the Spring Data Examples.
If at all Spring related that would be relevant to Spring Data JPA https://jira.spring.io/projects/DATAJPA
But so far this looks completely independent of Spring.
I retagged the question on SO accordingly. 
If that doesn't attract any help you might want to try the Hibernate Forums: https://forum.hibernate.org/
