### ISSUE TITLE
Question for generic repository autowiring

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [spring-projects/spring-data-examples#406]
My question is regarding an issue of autowiring the bean of a repository eg. in a unit test or a Service.

My problem is that it throws the following Exception:
```
    09/12-14:10:12.516 [main] ERROR TestContextManager:234 - Caught exception while allowing TestExecutionListener [org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@33c7e1bb] to prepare test instance [com.acme.persistence.repository.AcmeRepositoryTest@1a1f5f71]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.acme.persistence.repository.AcmeRepositoryTest': Unsatisfied dependency expressed through field 'repo'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'acmeRepository' is expected to be of type [com.acme.persistence.repository.PerformanceRepository] but was actually of type [com.sun.proxy.$Proxy55]
```

My configuration is as described in https://spring.io/blog/2011/02/10/getting-started-with-spring-data-jpa/. 
I have nevertheless a generic interface for the repo.
```
@Transactional
public interface AcmeRepository <T extends TestEntity> extends JpaRepository<T, Long> { … }
```
But when autowiring the AcmeRepository like below the code fails to run.
```
    @RunWith(SpringJUnit4ClassRunner.class)
    public class AcmeRepositoryTest {

	@Autowired
	AcmeRepository repo;

    ...

    }
```

My question is, what could have caused an exception as such.

Thank you!

**Comment by mp911de** [comment]
This issue tracker is for bugs or improvement of the examples and not a general forum. 
Your question sounds like an ideal for Stackoverflow https://stackoverflow.com/questions/tagged/spring-data-jpa. Make sure to attach some more code like the configuration or even a GitHub repo link.
