### ISSUE TITLE
spring-data-elasticsearch Ipv6

### ISSUE THREAD

**Issue by yinyanzhang** [spring-projects/spring-data-examples#425]
How to deal with the ipv6 elasticsearch host in application.properties file？like “[2001:3CA1:10F:1A:121B:0:0:10]:9300,"

**Comment by schauder** [comment]
This issue tracker is for bugs and improvements of the examples only.
For bugs and feature requests on the individual modules please use [the respective issue tracker](https://jira.spring.io/projects/DATAES).
For questions about how to use a module ask [a StackOverflow question with the appropriate tag](https://stackoverflow.com/questions/tagged/spring-data-elasticsearch).

Feel free to leave a link to the question here.
