### ISSUE TITLE
Could you please guide me how did you save data for @Reference List<Person>

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-data-examples#428]

**Comment by schauder** [comment]
This issue tracker is only for improving the Spring Data examples. 

For questions how to use Spring Data create a question over at StackOverflow tagged with the appropriate tag `spring-data-xyz` where xyz is the Spring Data module you have a question about.
Feel free to leave a link to the question in a comment.

This sounds like a really basic question which might be answered by reading the documentation and/or a tutorial for the module in question.

**Comment by JavaHelper** [comment]
@schauder - Could you please post answer although its easy for you ? For a newbie like me, I really did not get anything from the doc. Please help
