### ISSUE TITLE
How to perform IgnoreCase Queries in redis?

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-data-examples#429]

**Comment by schauder** [comment]
This issue tracker is only for issues regarding the Spring Data Examples. 
For usage questions regarding one of the modules please refer to [StackOverflow using the appropriate tag](https://stackoverflow.com/questions/tagged/spring-data-redis). 

Feel free to leave a link to the question here.

**Comment by JavaHelper** [comment]
Please guide here : https://stackoverflow.com/questions/53134556/caused-by-java-lang-illegalargumentexception-containing-1-iscontaining-co

**Comment by JavaHelper** [comment]
I dont see any response on this. I expect to update Spring Doc so that newbie can understand out of it.
