### ISSUE TITLE
java.lang.IllegalArgumentException: IN (1): [IsIn, In]is not supported for redis query derivation

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-data-examples#430]

**Comment by JavaHelper** [comment]
Before closing the issue, please reply with some details

**Comment by odrotbohm** [comment]
This is the issue tracker for the Spring Data examples. For issues in Spring Data Redis, please use [the project’s tracker](https://jira.spring.io/projects/DATAREDIS).

**Comment by schauder** [comment]
This issue tracker is only for issues regarding the Spring Data Examples.
For usage questions regarding one of the modules please refer to [StackOverflow using the appropriate tag](https://stackoverflow.com/questions/tagged/spring-data-redis).

If this is a bug or missing feature in one of the modules, please create an issue in the [respective issue tracker](https://jira.spring.io/projects/DATAREDIS/issues).

Feel free to leave a link to the question here.

> Before closing the issue, please reply with some details.

Sorry, but I can't/won't.

1. There is no question. Just an exception. That might have all kinds of reasons.

2. I know very little about Redis, so even if there is a question I won't be able to answer it, at least not without some research.

3. Others searching for the same problem/feature/bug won't find it here.
