### ISSUE TITLE
Could you please guide me here https://stackoverflow.com/questions/53251523/redis-data-modeling-for-many-to-many-relationship ?

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-data-examples#431]

**Comment by odrotbohm** [comment]
Please stop opening tickets that are obviously not suitable for this tracker. Even more so, please stop cross posting SO posts.

**Comment by JavaHelper** [comment]
Your Spring Redis docs is not clear to get answer of all these queries. Some more examples should be provided into the code and the code is mere basic now. I hope to get answers from you (your team), atleast guide on the same.

Also, I had been asked to put a stackoverflow.com link here for any issues, thats why I added that.

**Comment by schauder** [comment]
The idea behind "leaving a link" was to add a comment with a link to the question on the original issue.

**Comment by JavaHelper** [comment]
Could you please have a look at the query and guide ?  Also please guide on https://stackoverflow.com/questions/53265496/how-to-model-data-in-redis-for-values-complex-data-structure

**Comment by odrotbohm** [comment]
One last time. Please stop this behavior. You have posted you StackOverflow and there is no reason to bind other people’s time by asking for comments in this tracker. You’re spamming.

I’d hate to do this but I guess we have to block you should that behavior persist.

Thanks for understanding.
