### ISSUE TITLE
Sort/Order By

### ISSUE THREAD

**Issue by guntutur** [spring-projects/spring-data-examples#442]
how to achieve data retrieved from redis with sort/order by?

i have tried adding sort param of 

> PageRequest.of(1, 10, Sort.Direction.ASC, "another")

another one is using jpa styled order by clause like this 

> findBySomeAndThingOrderByAnotherAsc

none of them seems to work, the data type i use to order is of type Integer, any pointer is highly appreciated, thanks

**Comment by schauder** [comment]
This is the issue tracker for the examples. 

For general support questions please post a question on [Stackoverflow](https://stackoverflow.com/questions/tagged/spring-data-redis).
