### ISSUE TITLE
StoredProcedure resultSetMapping

### ISSUE THREAD

**Issue by zacader** [spring-projects/spring-data-examples#453]
call sqlserver StoredProcedure use @Procedure  return some fields of the entity class and map the result set

`  
@NamedStoredProcedureQuery(name = "ListProjects", procedureName = "[dbo].[yea_ListProjects]",
                parameters = {@StoredProcedureParameter(mode = ParameterMode.IN, name = "CheckerID", type = String.class)}
                , resultSetMappings = {"ProjectsMapping"}
        )
@SqlResultSetMapping(name = "ProjectsMapping", entities = @EntityResult(entityClass = Projects.class,
        fields = {@FieldResult(name = "sn", column = "[sn]"),
                @FieldResult(name = "code", column = "[Code]"),
                @FieldResult(name = "project", column = "[Project]"),
                @FieldResult(name = "address", column = "[Address]"),
                @FieldResult(name = "displayOrder", column = "[DisplayOrder]")}))
`

fields:
`
@Id
    @Column(name = "[sn]")
    private Long sn;

    @Column(name = "[Code]", nullable = false)
    private String code;

    @Column(name = "[Project]", nullable = false)
    private String project;

    @Column(name = "[Address]")
    private String address;

    @Column(name = "[Latitude]")
    private Double latitude;

    @Column(name = "[Longitude]")
    private Double longitude;

    @Column(name = "[ProgressA]", nullable = false)
    private Long progressA;

    @Column(name = "[ProgressB]", nullable = false)
    private Long progressB;

    @Column(name = "[ProgressC]", nullable = false)
    private Long progressC;

    @Column(name = "[FaultA]", nullable = false)
    private String faultA;

    @Column(name = "[FaultB]", nullable = false)
    private String faultB;

    @Column(name = "[FaultC]", nullable = false)
    private String faultC;

    @Column(name = "[CheckerIDA]")
    private String checkerIda;

    @Column(name = "[CheckerIDB]")
    private String checkerIdb;

    @Column(name = "[CheckerIDC]")
    private String checkerIdc;

    @Column(name = "[DisplayOrder]", nullable = false)
    private Long displayOrder;

    @Column(name = "[Created]", nullable = false)
    private java.sql.Timestamp created;

    @Column(name = "[Modified]", nullable = false)
    private java.sql.Timestamp modified;

    @Column(name = "[Memo]")
    private String memo;

    @Column(name = "[Flag]", nullable = false)
    private Long flag;

    @Column(name = "[Status]", nullable = false)
    private Long status;

    @Column(name = "[ProjectType]")
    private String projectType;
`

method in Repository interface
`
@Procedure(name = "ListProjects")
    List<Projects> getListProjects(@Param("CheckerID") String checkerID);
`

It's doesn't work，How to solve ?

**Comment by schauder** [comment]
This issue tracker is for bugs and improvement requests for the Spring Data Examples only.
Please use StackOverflow for general usage and support questions.
