### ISSUE TITLE
Redis Cluster Config Endpoint Issue 

### ISSUE THREAD

**Issue by deepshiv126** [spring-projects/spring-data-examples#496]
Hello,

This is not an issue, but asking for suggestion - I have been searching, but unable to find right answer, so posting it here, hoping to get some help!

I am trying connect to aws-elasticache-cluster-enabled endpoint using Spring Data Redis in combination with Jedis Library. 

Here is how my code looks like 

```
final List<String> clusterNodes = Arrays.asList(
"node1.use1.cache.amazonaws.com:6379",
"node2.use1.cache.amazonaws.com:6379");

JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setMaxTotal(250);
        poolConfig.setMinIdle(0);
        poolConfig.setMaxIdle(1);
        poolConfig.setBlockWhenExhausted(false);
        poolConfig.setJmxNamePrefix("POLARIS-REDIS-POOL");
        poolConfig.setTestOnCreate(true);

JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(new RedisClusterConfiguration(clusterNodes), poolConfig);
jedisConnectionFactory.afterPropertiesSet();

final RedisTemplate<String, Serializable> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(jedisConnectionFactory);
        redisTemplate.setKeySerializer(new JdkSerializationRedisSerializer());
        redisTemplate.setValueSerializer(new JdkSerializationRedisSerializer());
        redisTemplate.afterPropertiesSet();

final StringRedisConnection stringRedisConnection = new DefaultStringRedisConnection(redisTemplate.getConnectionFactory().getConnection());
final String message = stringRedisConnection.echo("Hello");
System.out.println("Hello".equals(message));
```

Question 1: What's wrong with above code ? Why I am not able to create RedisTemplate or establish connection to Redis Cluster ?

Question 2: Instead of node endpoints, is there any way I can use Cluster Config Endpoint Point ( NOT Primary EndPoint) ?

Any reference link or suggestion, is really appreciated?

For some strange reasons, at spring-data-examples/redis - cluster - example - I m not able find any example there! am I missing something there.

**Comment by christophstrobl** [comment]
Please use [Stackoverflow](https://stackoverflow.com/tags/spring-data-redis) for questions and the [bug tracker](https://jira.spring.io/projects/DATAREDIS) to report issues related to the projects used in the examples. Thank you!
