### ISSUE TITLE
Return result to entity with relationship executes additional queries

### ISSUE THREAD

**Issue by altancabal** [spring-projects/spring-data-examples#498]
When the returned element is an entity with relationships like the LegoSet (with many models), then a query is executed for every element in the result.

For example, if you add `repository.findAll();` at the end of the `customQueries()` test, after the first query is executed, an additional query is executed for every model in the result. Is this the expected behaviour?

https://github.com/spring-projects/spring-data-examples/blob/7b0c7a539b4d02ce6e214978f5e113c959a50f8f/jdbc/basics/src/test/java/example/springdata/jdbc/basics/aggregate/AggregateTests.java#L113

**Comment by schauder** [comment]
Yes, this is currently the expected behavior.

We will eventually improve on that.
You might want to create an issue for this over at https://jira.spring.io/projects/DATAJDBC

This GitHub issue tracker is only for bugs/feature requests regarding the examples.
