### ISSUE TITLE
How to invoke Face ID registration from my app in Android Device in React Native

### ISSUE THREAD

**Issue by Abyindu** [spring-projects/spring-data-examples#511]
Hi All

I am facing the below challenge

Trying to setup a face id authentication in a new app we are building in react Native
Consider the below scenario 
face id is not registered in the android device 
User wanted to register for face id authentication from the app we are building.
Query : How to invoke Face ID registration of the device from the app so that user can first register their face id in the device.

Can some one help

**Comment by schauder** [comment]
This issue tracker is for bugs and improvement requests for Spring Data Examples. 
The right place for general usage questions of Spring Data is StackOverflow.

While your question doesn't seem to be Spring Data related StackOverflow might still be a good place to ask it.

**Comment by Abyindu** [comment]
@schauder thank you .
