### ISSUE TITLE
How to use database index when i use jpa Example

### ISSUE THREAD

**Issue by farsunset** [spring-projects/spring-data-examples#512]
```
Message condition = new Message();
condition.setReceiver(account);
condition.setChannel(channel);
condition.setState(MessageState.INITIAL);
```

return messageRepository.findAll(Example.of(condition),Sort.by("createTime").descending());

In mysql the receiver has index.  so i want receiver is first all in the where . but it not , The Generated  sql is :
where
        message0_.channel=? 
        and message0_.state=0 
        and message0_.receiver=? 

**I want:**
where
        message0_.receiver=? 
        and message0_.channel=0 
        and message0_.state=? 

How to assign property sort to generated sql? thanks

**Comment by schauder** [comment]
This is the issue tracker for Spring Data Examples. It's for bugs and improvement requests for the examples only. 

Yours looks like a general usage question for which StackOverflow would be the right place.
