### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by 3792274** [spring-projects/spring-data-examples#527]
example.users.UserRepository
location:   spring-data-examples\web\querydsl\src\main\java\example\users\UserRepository.java
reason： can't find  class  **QUser**

**Comment by mp911de** [comment]
Please build the project with Maven on the command line to activate annotation processing for Querydsl. See [Travis CI build](https://github.com/spring-projects/spring-data-examples/blob/master/.travis.yml#L46) for further reference.

**Comment by 3792274** [comment]
@mp911de  
**perfect**  Thank You!
