### ISSUE TITLE
how to implement an audit interceptor when using @Query?

### ISSUE THREAD

**Issue by halower** [spring-projects/spring-data-examples#535]
I have an audit interceptor very similar to this : http://www.mkyong.com/hibernate/hibernate-interceptor-example-audit-log/

Whenever i do in my service method:
```
 User user = this.userRepository.findOne(id);
 user.setX(x);
 user.setY(y);
I get an audit just fine! works perfect.
```

But when i use a query from whithin the respository like so:

```
UserRepository {
   @Query("UPDATE User u SET u.password = ?2 WHERE u.id = ?1 ")
   @Modifying
   public void updatePassword(Long userId, String encodedPassword);
}  
```
I always thought that since spring-boot-jpa supports @Query, it definitely supports auditing. However, the reality is very bad. The official documentation is not clear enough, so I have dug a big pit.，because my project is nearing the end, only to find this problem, so it is impossible to switch other ways, do not know how to solve it, or alternatives，I hope everyone can help me, I will wait for results online.

**Comment by schauder** [comment]
This is not so much a limitation of Spring Data JPA, but of JPA.
The Spring Data JPA reference documentation states clearly in my opinion that Auditing is build on an `EntityListener`.

The workaround ist to load the entities using the where clause used in the update statement and either update them one by one thereby triggering events or to include the auditing information in the update.

If you still think a documentation update is in place feel free to create an issue in the issue tracker for Spring Data JPA: https://jira.spring.io/projects/DATAJPA but note that we have no interest to replicate JPA documentation or create a "JPA Gotchas" kind of document.
