### ISSUE TITLE
R2DBC example test fails because of version collision with jOOQ

### ISSUE THREAD

**Issue by fjacobs** [spring-projects/spring-data-examples#542]
Steps to reproduce:
1. Checkout spring-data-examples
2. Run mvn test

The test fails because JooQ uses h2 database: 1.4.199 and r2dbc-h2 0.8.0.BUILD-SNAPSHOT uses version 1.4.200.

If you want I can open a pull request to change the version of r2dbc-h2 to 0.8.0.RC2 since it uses the same version of H2 as JooQ?

**Comment by mp911de** [comment]
R2DBC H2 requires H2 1.4.200 and R2DBC is the project that requires the most up-to-date dependencies to avoid method signature errors. Upgrading to Spring Boot 2.2.1 should be able to resolve these issues.

**Comment by mp911de** [comment]
Spring Data examples are now upgraded to Spring Boot 2.2.1 and the CI build is back to green.
