### ISSUE TITLE
Too many Cluster redirections?

### ISSUE THREAD

**Issue by whbq** [spring-projects/spring-data-examples#550]
org.springframework.data.redis.TooManyClusterRedirectionsException: Too many Cluster redirections?; nested exception is redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
docker run redis cluster

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Currently, the Examples build is running fine: https://travis-ci.org/spring-projects/spring-data-examples/jobs/645427714

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
