### ISSUE TITLE
likeIgnorecase : Illegal operation lower(meal.title) like %%

### ISSUE THREAD

**Issue by gaetan224** [spring-projects/spring-data-examples#558]
Hello,
seems as if the likeIgnorecase  operation is not supported in mongodb support

Spring Boot : 2.1.10.RELEASE
querydsl-apt: 4.2.1
querydsl-mongodb: 4.2.1

**Comment by kpundru** [comment]
Is the problem solved?

**Comment by christophstrobl** [comment]
Please use the [issue tracker](https://jira.spring.io/projects/DATAMONGO/) of the specific project to report problems. Thank you!
