### ISSUE TITLE
How to handle “duplicate error” in Mongo BulkInsert retry

### ISSUE THREAD

**Issue by tvdinh** [spring-projects/spring-data-examples#560]
I'm inserting a large number of documents to a Mongo DB using bulkWrite operation (Java Driver 3.12). I have also implemented a retry mechanism in case of connection disruption.

But there is an issue in the subsequent retries: As some documents have been inserted in previous try, the subsequent try result in `Duplicate Key error`

```java
    @Autorwire  
    private ReactiveMongoOperations operations
    operations
        .execute(Document.class, collection ->
 collection.bulkWrite(insertOneRequests, new BulkWriteOptions().ordered(false)
        .bypassDocumentValidation(true)))
        .retryWhen(Retry.any().fixedBackoff(Duration.ofMillis(backoffDuration)).retryMax(retryCount)
        .doOnRetry(retryContext -> log.info("Retry"));

```

Is there a way to ignore the "Duplicate Key Error" in subsequent retries ? 

Given it is not an uncommon scenario, how is normally handled ? Assuming that I'm trying to avoid using "Upsert"(Replace) operations in this case.

**Comment by christophstrobl** [comment]
Please use the project specific [bug tracker](https://jira.spring.io/projects/DATAMONGO/) to report issues and [Stackoverflow](https://stackoverflow.com/questions/tagged/spring-data-mongodb) for general questions. Thank you!
