### ISSUE TITLE
Missing @Transactional in jpa showcase

### ISSUE THREAD

**Issue by Javabien** [spring-projects/spring-data-examples#568]
In the original [article](https://spring.io/blog/2011/02/10/getting-started-with-spring-data-jpa/), the use of `@Transactional(readOnly = true)` was encouraged in both before/after implementations, but here it's not part of the after:

```
@Transactional(readOnly = true)
public interface CustomerRepository extends JpaRepository<Customer, Long> { … }
```
VS

https://github.com/spring-projects/spring-data-examples/blob/master/jpa/showcase/src/main/java/example/springdata/jpa/showcase/after/CustomerRepository.java#L30

**Comment by schauder** [comment]
`SimpleJpaRepository`, the implementation of `JpaRepository itself is annotated with `@Transactional(readOnly = true)` therefore it is not necessary for the `CustomerRepository`.

This was introduced a few months after the Blog article: https://github.com/spring-projects/spring-data-jpa/commit/159ea28f880554246417f53417e338539dc8e3a2

**Comment by Javabien** [comment]
Thanks for sharing the link, but I still have a more general question than, why transactions are no longer part of the "default"?  To my understanding, the JPA cache is built based on the transaction, so it's better to keep it also for read operation, the `readOnly = true` gives some performance improvement.

**Comment by schauder** [comment]
I'm not sure what you mean. The `@Transaction` annotation is still there, you just don't have to put it there explicitely.

**Comment by Javabien** [comment]
Oh sorry, I didn't pay enough attention to the end of the PR, so they simply moved the `@Transactional(readOnly = true)` from the interface `JpaRepository` to the implementation `SimpleJpaRepository`, which means we don't have to put it explicitly on top of all the interfaces we are creating.
