### ISSUE TITLE
Add Spring Data example for r2dbc-mssql

### ISSUE THREAD

**Issue by darkmastermindz** [spring-projects/spring-data-examples#575]
@mp911de As of writing this, we are on Spring Data R2DBC 1.1.1.RELEASE and latest r2dbc-mssql 0.8.3.RELEASE. Would like to see examples of implementing r2dbc database connection, repositories, and rest controller with the latest versions as there are currently no working examples.

**Comment by mp911de** [comment]
The R2DBC example at https://github.com/spring-projects/spring-data-examples/tree/master/r2dbc/example shows an example using `DatabaseClient` and a repository. Since our examples are focussed on the particular database technology, we don't intend adding a full application around it.
