### ISSUE TITLE
Migrate examples to JUnit 5

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-examples#583]
Spring Boot 2.4 advocates for JUnit 5 usage so we should start migrating our examples to use JUnit 5.

**Comment by mp911de** [comment]
I'm going to take care of the MongoDB to JUnit 5 migration.

**Comment by mp911de** [comment]
Geode is the only remaining module to be migrated to JUnit 5.

**Comment by saurabh-slacklife** [comment]
Hey, @mp911de do you mind if I pick up changes for Geode? If you think I can, I'll prefer small PRs.

Let me know if I can help.

-S
