### ISSUE TITLE
[R2DBC-Spring-Data-kofu]:Expressing distinct in criteria API

### ISSUE THREAD

**Issue by cheroliv** [spring-projects/spring-data-examples#598]
Hello I try to convert a jpql query to the criteria api.
the sql query is
```SELECT COUNT(DISTINCT id) FROM `user` WHERE login != :anonymousUser```
I've just succeed to reach this query with criteria
```SELECT COUNT(id) FROM `user` WHERE login != :anonymousUser```
here is the code:
```
class UserRepository(
    private val repo: R2dbcEntityOperations
) {
    companion object {
        @JvmStatic
        private val userModel by lazy { User::class.java }
    }

    // expected query:
    //"SELECT COUNT(DISTINCT id) FROM `user` WHERE login != :anonymousUser"
    fun countAllByLoginNot(anonymousUser: String): Mono<Long> {
        return repo.select(userModel)
            //current query:
            //"SELECT COUNT(id) FROM `user` WHERE login != :anonymousUser"
            .matching(
                query(
                    where("login")
                        .not(anonymousUser).ignoreCase(true)
                )
            )
        .count()
    }
}
```

How do I introduce the distinct with criteria API?

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature requests for the Spring Data Examples. 

The question you are asking is just a usage question and not even for Spring Data, but purely JPA based.

We recommend asking such questions on Stackoverflow.
They are off topic here.

**Comment by schauder** [comment]
This issue tracker is for bug reports or feature requests of the Spring Data Examples. 

This is a usage question which should be asked on Stackoverflow.

**Comment by cheroliv** [comment]
> This issue tracker is for bug reports or feature requests of the Spring Data Examples.
> 
> This is a usage question which should be asked on Stackoverflow.

That kind of question could only help to complete the lack of documentation.
Why didn't you take this as a documentation feature request. 
I asked that question on stackoverflow and on github issue at the same time with the same statement.
here you have the bad education to answer me like if I was your child, but you did not respond to it on stackoverflow. STFU or be util.

**Comment by schauder** [comment]
> STFU or be util.
Please stay friendly.

> Why didn't you take this as a documentation feature request.
Because it just costs time to guess what people want to happen with an invalid request. 
If you want us to consider it a feature request for documentation improvement, you are welcome to create one against spring-data-r2dbc.
