### ISSUE TITLE
Update the elastic search example to use High level Rest client APIs

### ISSUE THREAD

**Issue by wolfdale** [spring-projects/spring-data-examples#610]
Currently spring data elasticsearch example is using a deprecated client ```NodeClientFactoryBean```. We should upgrade example to use Java High Level REST Client.

**Comment by mp911de** [comment]
Blocked currently by https://github.com/spring-projects/spring-data-examples/pull/609.

**Comment by wolfdale** [comment]
PR https://github.com/spring-projects/spring-data-examples/pull/612
