### ISSUE TITLE
Update the Elasticsearch setup to the current version 8 of  Elasticsearch.

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-examples#660]
Spring Data Elasticsearch since version 5.0 uses the Elasticsearch library in version 8, this should be reflected in the setup of the sample as well. I will update this, but I'm not sure if this will be done before the release of 5.1 in May

**Comment by hafza7869** [comment]
With support of elasticsearch 8.x you should also include a guide to connect spring boot application with spring data elasticsearch with https and security enabled, I am unable to find any solution for this, I have done lots of research but everyone who is using the elasticsearch is first going to disable the security in the elasticsearch and then connect it with the spring boot application, which should not be the case.

**Comment by sothawo** [comment]
Donw with 21830b313808d96150da70bf43f4c0f6bab03b08 and aa6fccc07e925071c0c88540396877649c74b625
