### ISSUE TITLE
Add example of Kotlin Coroutine and Reactive MongoDB mixture

### ISSUE THREAD

**Issue by PikachuCacik** [spring-projects/spring-data-examples#680]
There seems to be no example of using the `CoroutineCrudRepository`. 
I am willing to take this issue since I am learning about the CoroutineCrudRespository.

**Comment by mp911de** [comment]
Have you seen https://github.com/spring-projects/spring-data-examples/blob/main/mongodb/kotlin/src/test/kotlin/example/springdata/mongodb/people/FlowAndCoroutinesTests.kt?

**Comment by PikachuCacik** [comment]
yup but isn't this for tests? I meant Webflux with coroutines for repository, controller, etc.

**Comment by mp911de** [comment]
Spring Data examples are focussed on Spring Data and not a general-purpose yard for all sorts of samples.
