### ISSUE TITLE
Add example for calling Stored Procedure with multiple OUT parameters

### ISSUE THREAD

**Issue by cmoro-deusto** [spring-projects/spring-data-examples#80]
I couldn't find anywhere if there's a way to call a SP with multiple out params using @Procedure notation

**Comment by thomasdarimont** [comment]
Hi Carlos, AFAIK we don't support that at the moment. 
Currently we support exactly one output parameter mapped to the return value of the `@Procedure` annotated method call.

I could imagine that we could support custom result structures where multiple output values are mapped to their fields. What would be your suggestion for such an API?

Cheers,
Thomas

**Comment by mp911de** [comment]
Closing this ticket as we have https://jira.spring.io/browse/DATAJPA-707 and https://jira.spring.io/browse/DATAJPA-748 to track calling stored procedures with multiple out parameters.

**Comment by mhewedy** [comment]
What about Mapping result sets as well?

**Comment by abhinayneo** [comment]
CREATE PROCEDURE `SP_DIVI_SELECT`(
	IN p_USER_ID VARCHAR(50)
)
BEGIN
	SELECT DIV_NAME,
    ADDRESS, NUMBER,
    ACTION 
	FROM DIVI 
	WHERE USER_ID=p_USER_ID;
end

anybody tell me
