### ISSUE TITLE
Add example of how to use RestTemplate as HAL client

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-data-examples#85]

**Comment by lubosek** [comment]
Hi, thanks for the example but to be honest I still don't get how the magic happens that the client is able to parse HAL body. RestTemplate has some default message converters registered but AFAIK the one for HAL is not among them and I don't see any code that adds it. :-(

**Comment by olivergierke** [comment]
The registration is part of Spring Boot transparently enabling `@EnableHypermediaSupport` which adds the necessary message converters to all `RestTemplate` instances available in the `ApplicationContext`.
